### ISSUE TITLE
missing coin: Zclassic (ZCL)

### ISSUE THREAD

**Issue by kfatehi** [quoid/coin-ticker#20]
can't find it in the settings.

running version 1.1.1

**Comment by quoid** [comment]
I'll add it next version; I still have a lot of coins I need to add.

**Comment by quoid** [comment]
Next update will add the following 87 coins:

Name | Symbol
-- | --
AChain | ACT
aelf | ELF
Agoras Tokens | AGRS
AirSwap | AST
Ambrosus | AMB
BLOCKv | VEE
Bread | BRD
BridgeCoin | BCO
Burst | BURST
Centra | CTR
ChainLink | LINK
Cindicator | CND
CloakCoin | CLOAK
Cobinhood | COB
CoinDash | CDT
CyberMiles | CMT
DECENT | DCT
Decentraland | MANA
Decision Token | HST
DeepBrain Chain | DBC
Dentacoin | DCN
DigitalNote | XDN
district0x | DNT
Dynamic Trading Rights | DTR
Einsteinium | EMC2
Enigma | ENG
Enjin Coin | ENJ
Etherparty | FUEL
ETHLend | LEND
Experience Points | XP
FirstBlood | 1ST
Flash | FLASH
Genesis Vision | GVT
Gifto | GTO
Grid+ | GRID
Gulden | NLG
HempCoin | THC
Hshare | HSR
iExec RLC | RLC
IoT Chain | ITC
iXledger | IXT
Jinn | JINN
Kin | KIN
KuCoin Shares | KCS
LAToken | LA
LBRY Credits | LBC
Lunyr | LUN
Medibloc | MED
Melon | MLN
Modum | MOD
Mooncoin | MOON
Neblio | NEBL
Nuls | NULS
Oyster Pearl | PRL
PACcoin | PAC
Peercoin | PPC
Pillar | PLR
Po.et | POE
RChain | RHOC
Red Pulse | RPX
SHIELD | XSH
Shift | SHIFT
Simple Token | ST
SIRIN LABS Token | SRN
Skycoin | Sky
SmartCash | SMART
Snovio | SNOV
SpankChain | SPANK
Storjcoin X | SJCX
Storm | STORM
Tierion | TNT
Time New Bank | TNB
Triggers | TRIG
Ubiq | UBQ
Unikoin Gold | UKG
UTRUST | UTK
Viacoin | VIA
Viberate | VIB
Voxels | VOX
WaBi | WABI
Wagerr | WGR
WAX | WAX
Xenon | XNN
XPlay | XPA
XTRABYTES | XBY
ZClassic | ZCL
ZenCash | ZEN

**Comment by kfatehi** [comment]
Holy guacamole!

**Comment by quoid** [comment]
resolved here: 979d936e9bde4a978cd24431f8260838c02da1a5
